### ISSUE TITLE
Zach's feedback

### ISSUE THREAD

**Issue by caseyg** [SFPC/sfpc.github.io#40]
I made a checklist below, let's discuss this stuff. I think a lot of it is not necessarily things to "fix" but to discuss and plan around revising together. Some of it is also already on our radar.
- [ ] ~~menu is weird on mobile~~ moved to #45 
- [x] ~~alot of image seem really big, we should have some thumbnail system in place.   loading seems really slow on some pages.  see for example images like http://sfpc.github.io/img/projects/haze.png~~ closed by Zach
- [ ] ~~would be awesome to see people details without a subpage~~ moved to #47 
- [ ] ~~classes might be better as "sessions", classes vs courses seem odd to me~~ moved to #48
- [ ] ~~also, I'm not really clear what the difference is between a course and a workshop - it might be useful to have a paragraph explanation or some text?  Some courses should be workshops I think too since they were just one day things)~~ moved to #48
- [x] can we drop the mini thumbs on the classes page?  they are not very helpful I think.  People could be a link to their profile, etc. 
- [x] ~~overall, I wonder if we could have something to tone down the color on pages with a lot of images like http://sfpc.github.io/courses/ - maybe a greyd out version of the image until you mouse over?  I find it kind of distracting since these images are really different.  I could imagine a much more subtle way to use them.~~ closed by Zach
- [ ] ~~the columns have huge gaps at certain brorswer widths, can we make the gap fixed, like the menu is?~~ duplicate of flexbox problems issue #12 
- [ ] ~~more padding between menu and content and footer~~ related to #12 flexbox layout problems fix
- [ ] ~~we lost info about founders (about?), maybe we could have a history section or something where we can have a bit more credit...~~ related to Taeyoon's edits #44 will make into a new issue
